name: clrun

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            ext: tar.gz
          - os: macos-latest
            target: x86_64-apple-darwin
            ext: zip
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            ext: zip

    steps:
      - uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      - name: Build
        run: cargo build --release --target ${{ matrix.target }}

      - name: Package binary
        run: |
          cd target/${{ matrix.target }}/release
          BINARY_NAME=clrun
          if [[ "${{ matrix.ext }}" == "zip" ]]; then
            7z a ${BINARY_NAME}-${{ matrix.target }}.zip $BINARY_NAME.exe || 7z a ${BINARY_NAME}-${{ matrix.target }}.zip $BINARY_NAME
          else
            tar -czf ${BINARY_NAME}-${{ matrix.target }}.tar.gz $BINARY_NAME
          fi
        shell: bash

      - name: Upload to Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/${{ matrix.target }}/release/clrun-*.${{ matrix.ext }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
